language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG .
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG
  on:
    tags: true
env:
  global:
  - secure: GuvPDgjSAwMribEXXaaUEaK6jplF2jt7QAh3Ltkit4Q3lmZieLEj555vCwMzL1CyOfIDnlx7tR18XoxS8UrU5VF1iG7zCG7UnHuwnzabJa1QplXagmVhxWmA0VsdKTN5uH9/jNP72/1Cj3K1qGEGZukBjE4VX7DbF5CXVV8Zs+Ahh3QyErgfqs//F140YbEVtQSy4F7ooY84pRjCD9FItAi5LWCDL0cOehvxa4CCIklGqnc28Ocx0Hpuar8g+SSYCm+EiJcr5J5C3lQd5vmMNVMWhVRuhsX4qK+6xPpJg2ObHFPFWmQy89SdZi4/2jO3ga7SZSnzdjb/hKyVRpGBvEmPOKcU47nZ2pWBKLAry1JQlCJLoX2cFgOEFsVfZkDiUgHo/rcs4xxZGcuVex/768WUTylOgX3EQYJBG52wtq2RovaOUksL9YU+FrB0jTXitU57/lUDHyGTvS8GFlgWPpTlZ0rYq1Ce9s4pRBFj9ChhDntCNGALd9r6H7G5bykvG2AjlgX91F8Qs/1YrzEmq/tZCyChnyVpZbshHd9oC4LLAhw6ozAcBSyFRt15FW3hn0+/is0VXCtBAasBAllGBOOWx18JM4t8N48+J71zv9xODZmm3CfTnXZu88Y1o8R9UGVL4hwb02J1/qNMtB6hD6gNuIu2jikDJEZH4iV7Oy0=
  - secure: Guk2qHiaJu67JjuT2HwNOFCBHKCt+qLTeILeFmr+1romnmDgI7dmKeob3qR++OXHU2qNtzhFZmT4KaW6FYbQ/Rl2dNaQxE+MeKM0qLEmAZDTDoMULR5BmL72J7VqL6EyhGkNEafD2UdCIJFGdeczOcMGudYkQHYEs/N+TVk9o13BcyNR+dkNVZuPfrtVS9QrXjoY00b/R6ENmrMo4I90sjX6GUFGDBC+wnugNwlg+Ghwn37rOPC97IJWmaTmQK6jWPlcnfelgpoHrLRfzTkIIn2vD/CqcWXvYUkdNo/wgtbkkH1KcJr01bfVlOJZ5IJENpXmexjHhNvPhJT9JgTzVCy+eIik8ma77Ub5wzLVSCCGY3cBhAegPg/K4iVLaVTXcq67vk54uGHYDcEL5/fREyqksPT36oUAm2SlT+EHzu2uaBhQt7z81r0rkMizNImAkLg7Xqq3Dobu00EUILFmIxAXujZcfXlf5U1xpvLoMM9C8fvQ4E/fyDS4oyDu58x0S4wy9aNNz9k2neSYjO66/TTp4Yrs2QO6ersHVOkxdR1OPN+3rT1/9ZOOcS1dwioQv0bjyC684DFF+P3vyxiuzwzDWJc74gtMb1G1nWMwBS0QAyRzpcKWw+h/z6cjouVbmYpiGNj2anSRM+R96V8bi0QFf2mrluf/YknQP55i948=
