language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t cop-watch/portal .
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJ5RW7SQ4ABJPTLXA
  secret_access_key:
    secure: Yqds1jwij2GEfw4DKEdJfJU+BqTordlWyLto4xUXP+GQ9ANDl06NcPyp8zRBSFIEmBnLzYspxCudgEX1kzAMNm5Lv/1rTjovuOoD7cb1Dzv5BicH3zN0UzgEQJsrfvjr35n1taA2ZVZq5VxrqcN0hO0nGIE54xZKZEO6VZcBzznuOzpheU0kSZj1yKdLHFdy2V/MIMObnxThHFZd9OW9tImuwhd+J7VNWZAuiF/eewXdkB+i/z/c94zqdntgoA/04wAS2DjTgXaHvSYkAecpK7yLS85pIx2Gj4CtBSUpdmHE6sxA2eQ4YoVqd9AcxZyNbd78irtgX1HxOlX5IG6eIFRf96tsU0xFDGzr1pd1bU0ZrwcTnPuOiHvx2D03sozEqzOqrC1xxOqIroTwrpNPbpNkHjzL5TFpwiLs8L/kB8CMOCtR2FiMyjvVBigAzhpw/AgBrJvdkgVwwlYGpTKZ2zPPx2al2EDQDig3n0gtqZzqKVhUIWBKfeoJ51P9vrosu5d8z/32HtgJ86R6KB4W1th3JM4FKHMd9HZwkQxaQ6KdgCxkwv/apjmPkosQzFw8xDyUYh/8l9f4XiVp2LMiF+B7PSx1WsrBZAbywL7lYOUnV6Hz6cjIYpXgmfz4OIsrx1jvCW9ruO8Jy46uMo8g4GhCOz/RhaiGNqPJYN6uqIA=
  region: eu-west-1
  app: cop-watch
  env: cop-watch-production
  bucket_name: elasticbeanstalk-eu-west-1-106887332414
  on:
    tags: true
