language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG .
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG
  on:
    tags: true
env:
  global:
  - secure: Y8NEf84oXeDJyZYMsdbT9XeNDScAAAnh1pWOzxaI0lBrxNtGlErT0v+2dBS4bM2dRY4x9tf4GbvQf9Wt7vHiOsDRl9Xw1tE9682DR8WZ0UZuaM4pFy/cdSQXOl7hcvZQP63y8Vj4f8nVkxhI3SB2BDohJX2bH4iKulQqMRZy/xWv5DgD0W5vqMjv/UKZrde++P32dJwL+fw9ia7l/kvkixPi7tgZGkQ+EZvCBsXQO2TM2UHRvLO3oUqLnI9QabkLV/uKAH8uFJd2s9gxKaGUEgal6T5diKGyCA54F1TLeOLWAtCI9Nz9pm8P+3bma8ov9jIO7shgKtYnH3GYl+FQreLmcJYXVYcYD9lOpQA1NcRv6z4Wz7XwZUn2c0V+wSV/sioy34zhVtFT3qca0PMO4FCiYh0/q28ePzyFqPkVARoK5eQaHTl8YibEault4C59Mb4gvshFvq9iE2QGTiMo/XIP4AnquSYbwkRNx3LZAD9zrvZvc9MVpdJwimReXJ+n4hdLkcJAQh52MNOU6knaV0uEyp8zOelvQWQHM/dWIbAB48jdiTM8nQu0jkSgqHJpUAB3KUAs7mBcNz1JMsUBVhLOEk00+FEvvuKC26LRvN1TlJUrluNFJDc5GnM851drepHc72rpTqXBVvW9yVm38gBnlzKSvwQLzu9Wsw6yUsA=
  - secure: LQoJGct19zFTSACTcERNFtrZoglwQRcbgLdKGRNu61NtTfcRPrAJG9sC0FfJHMeGqNKhMnTRZr7nqAwoZ+1w0BPMVVBOvZkBpxXSXhZWkJD2kRO34OnyHurpLBxuOArg6up+Q5ATPWQS5L927tz7SLvYEyl+658vG4VLf29jDZ9Acw6mFEZWQhjwEhs3zDN39uhWBEISiSFe2nMM4M1ghdarjZ1SMLGAztj9Q3E62p78Vn/juNmDtajkq3CCBx7sTdAqn5uldXXDZObDWhIY1As5jZ20fz+SwHJCvTmzIDOwCptLvN9EMOcm3e6WAT6yFNF+MdsZdVxUuax0Br896TlTiVIZFUwRVSo1U0q9WDv3BdqbqOC64OrYM4Y7/YGjYWoc/ptQ3PunAg+/5DzCUalm8ugGeqfNkWi2FQMWthqIEwO+HUU0KLWqRcCkDVof1qGU21kahAszQO2HhHOs07lEHubEPs4W0rviYaFp5dsKx2KtSVWpYGnNrQvAp4qHL2e//B7yPXewr491q32NakUCFdISrJfwfQcuYRDLRmgexDt/RJWppTve1WGT8qEaXMxBgJKt7EaGJm6sUzHRb2lqjA/nmBBHrhYvscJ23Y/s3nucwgSuHB/iGEiGM2AjZiWd6ts1rdCACEWYXYFhNSad851275lfs94NjT437fE=
