language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t cop-watch/portal .
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIARLGWZLJY5VKNFA
  secret_access_key:
    secure: IQjdcdtiXN1jLOLUNy883nlyQVSr9FQyC3yjs4bNm9EwF8Vq7IzuR8RmJV86JHQkcJmbhtS9qcuzFb8TiQnSXWJVMMdaFsB0Xv/h2LiY6k6jQT0Rtf8T3/WdHOBjF8FG30CmuMJGxw9i1cJZUrIXe4BsOSsbJ91WCmPxungdbJb/dDPRXY2PsdnTuz6C1yRNGZeLus7+zyBX9tOV/ZaovDdI/1D53E0hTJ4jC0OOJARUbG83OXlPpxBdDayvkTjZCQK8bfHqlhKbk4wQRD8kSdOdVR2Hbu7uuI3tN7H+OVhtGp2wO7lC9gjRzRLnp3+RqFDap4JUZ3zYI84Gc809GQ7QEwUbACouBuut4h+p6H/CQVQ8R3prSYzIqo4qVhYMItEjtVvuKmMtPfrO/EwoDU00JINDgE2l8gxPm2YWoV2o5jGiphc/aMgtH8ZQLlHYxhwyx7TdYqNvJb3vLxlkWAPJq6scT5kdiIMtPWyfIOyPwPTvvnVC8NSiQX1RmgghnncLMD4f1sGZGDy6g/tRqV9PGsjtIlDSA/CzOxxo+Px5xVY0LKNOmpHgUOC1rURew/InfDVaQGa2VjH/70DNgBu0lHCGEsR7nfTLEeCP+0pIxh3qY233u42pl9sUACyd69+wL2znE0+VUowZ8XUYYtLO24D2CJgMtMjVuNfVdu4=
  region: eu-west-1
  app: cop-watch
  env: cop-watch-production
  on:
    tags: true
