language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG .
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG
  on:
    tags: true
env:
  global:
    - secure: "D8/gDr4JuOp+uyXgzautiFkl4TOFel2H62apJrR0K8fkzc7k7leAyQBbQU/+5wcB7nxv71HYBLuFLXzKgdkb+oHxfzpwq/gTw25t2RQigBQnFGuwatmY+PusdFYnPfLzxrORkKFMDtyyAJHgkdBLhwDhXaT7rj809xw6t7qakfB7usrcEWDGA3lX9Iqk9UPlDO9vpM0QqBrISn5Cbp71tgSrMETfx4jJCH49jojmXrM5TFli4/4p6zLukClM+9qkA873setVXXrwYE4i9q5YoAmsqs2ODyrrpkdM/Xqj7y/rFQtjlwFP718hqbxvLBtNqj2Gvn9VQYnIWmAn38+p8KxlUI0OuMImZtYX+esP3O2UrCIlJNJEqrLzofBxGRGXmZwpiscpkelpUlqW/8YafbIKdZ4k7MAJ7DfcYQocNSFp+yGAIHiGX4vyQZrGtuMUJ+hql1wI1njXGhit61t4k2Vc1JHQ83Km2q+leuDArGkis/MQmezAM3KRuMySegrxC9NmY/498gaaZODGGgB/vBJbqwkPCRec+NApHpaQuetgziT1O2AvB9hWWZjeaHz3eWO8OmKi1xkSgpDIjIUacP5qtmoUsNNn8KIXkUK9ea1J70CDqePqyw5l8KsBVtyV0txF0ZwpTN+tlbHuu8MLL3X2P3SQi7k5kBkTTd+4c7o="
    - secure: "Hs1qOrOPp3ymTz3bcdt5FvNqpdo/iyBVJkGdCYKU1/y4ximAO3bpqFs8IYAAFzkhj29pMh6e++5XCFHs6DyLO8D281ywKEHv7wIanEmFWDJpTIAGDvU/PMf3Y6YGXb+t6KFtE9tkibhNAO36YFQ/00oZAD6tAgvcjzG4BWwV5efC490wSvGQO8+ZAFe+GMWIRbnb8ODyH+eUKcqPdJ3riP3svDLj2bwvXYlYxpGu17HZxy5CC6xoTiw25XH471QmfUzafJQh9zAPs/NBXS91R5F/zD2bHpFLIio20GNT0OYzuOidJdJDemuxtAA3d7H7x8jy0NRfERC6H1tDrOTTK2zoG6xuw/eDZwBFIyVo9d02BPbcu1nL/V6h2daUdz4VVaNFBeiQjQjHJejeu8Dz8UHNnkHtxh4wFvd1/clPOYSP14GdSR2UyR0bPJvd24XGckaR97taBzKSRkuuUA+oO4uKjl4YG07uysv9YDwgnfqIOavh2K4YZVd4qhxZVqOEj6TKNRsmolV+fWGwc5LSZBWz0ICfyT3v7J5sBaOwujYySTb1Cqn4rEpBAoT+pzChMFfYJ0JhPuOUkMpIhNV8iKfqv3I8iKP1gDIgmzyk5tWcOcITclzrRN0TdltYzj0odStNW0hXowdnDy4F4hwmkURjIVZzkuIX+jlotwPsEBQ="
