language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t cop-watch/portal .
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJ5RW7SQ4ABJPTLXA
  secret_access_key:
    secure: SbdP+bvAUgMJyShiFPxfEezfgTHAg/c1NozM6uspUzgYYcWpcTHpdVAvqVh3oaOCkZYua0ZxeX/waRwXviczxiluwuyFgWW2r7jB5tQ+Ht+uMTKVFOD9NGn/SI4dhYYlVENz6b4LZ0GM7gRIs1KZebXEKKyIU0/H59B5cPH58n6llnyQ2XSfGTFhbEhvfmC8kGCQOgUNRY5AR7LQXtINqNAvCvy4Ja3rJ1V7sIlhsF+fgnIGFDAWyoAMQ7DnFfHjhtOJL7eb3Jm3old++zAqIKJrWHMbrRCn2lAFoQSujD6qTuQyELHhIO6xHxpl7dxrrVHJB9wFrX1i/+E0N8jC1HPYS9zvaAthPPptCDWWoeZRQhGR3gH4gFZZsVG0hb3Q3Ah6nWxt7u3adZqINH0N7SrvcXWS47iaiK3wQmde1b0z4Lqw5h2Bhk6UIjN359Dd6NBwpGxuoHPHhvYfLBz8lJoeXW9J3Al6LurZYwcnV8d+lsd5r0kbrfz5yYYvOfVkM351TifeblRxOfJymAAJJQgBOULC35ThALCO0n3tahgFLLZAcIMj4Ykxy9/vsrstSmBXJbxvLueKeEYbQWCREI4XbfGxKwzpTbhGu8b/VhoWYt8623rlx3Qvo3uMftNR+Cof7HC9oj0k+zjYTBN93jSOeiMvat+NcMw/9/gs6fE=
  region: eu-west-1
  app: cop-watch
  env: cop-watch-production
  on:
    tags: true
