language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t $DOCKER_USERNAME/cop-watch-portal:${TRAVIS_TAG:-latest} .
before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG
  on:
    condition: branch = master AND tag IS present
