language: node_js
node_js:
- node
cache:
- npm
addons:
  chrome: stable
services:
- docker
script:
- npm run e2e
- npm run test:ci
- npm run lint
- docker build -t $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG .
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/cop-watch-portal:$TRAVIS_TAG
  on:
    tags: true
env:
  global:
    DOCKER_USERNAME:
      secure: OM3Z/l4tXwelGGYIc3sJQDzWsuakEVEeRSg9eUF7/vCmHZobGzOETUX7m+A6TA49KK7PQhSiyQPmb5qaZMSZsQOSiCqtNPHwsxllvh3FyqktUEIqrc47oqr5PnSr0syhWFPeqdqBonUReyidbLBRC/7lxDF2DfHPhL1w8y6VMWR7/zf7ebXTg6g6Aee9gZAZBIzszP8QpKPqohWglmyZjPArBnH5PD5HkEfE7MNIyHLl2oTJQQVDFFrV3rCaw3xgim7OHpQRQpP7VUd5Y0Tv9nerT8eHyAXNHDj9gr6+qj2dIsjDwILsV0vcDT7pdksN31fEtyuIqTV7TEY6IvRj4YsicHfwCJzucSKKgFNxruacreDoaB6Rm5YB9yY8c4Wbr46T1pBNSPMNG9300tPnkU/6nlH/yrkWgiVb0J8PmVWxxWJOV2J4VmoW+b8fhutP0d0vflILHF4++0wYOdT0PxoJKg6nvrQd8BI+M7BNSyMDqJlV4LN4nP8QCCEUgWgNuClVQNp8tzphST1VymzAczDcyUfoRxYHYzwZ7TK2CraE1z4DMron5O7WAP+NbBDNOM+jtx1kQAkjPBBEmUjsdg4JbJ9dKP0LZzw+SeYAXL16eq2FqOLXeGBP2TNX3PcMfTad1NFqR/0+hAuXEnzV0EgbDSdu8Ig9CJLjtUrS+Fc=
    DOCKER_PASSWORD:
      secure: MuIs1/p4cdczHYjko+EEZye4v8HMhbQroEyBNuep4Fa8txgsYe1JFjXJYokHCw/BAqqTfhCM8kE21n07jBAztQtCd73RNZNhDYLz92YSW2yPBzGe3SU4Vad9A/H1MA9XoS2OP+l5xQYzOBleexOlM84UARjzh4rVoooXF5U4yOoYqfxWdxFRiq+mmjmRfE4tsW9K+QrvlxnJ9wxNAVNF/2vkwmQp+n0F23YWiWyufnAn5Kzl3jYy3wPdpDjVIn4W4Qp4MtLBNcdRyZ0yodPJLcEdwWIwRQVzxm9PbCKA5hAs6qV1UBc+zEIEHOnvsw4mSFBAJQfgliwkf2axTbIjmX1wIu3BmnPbREVNgxzOvbvx/xybPwxtCr8/rIL3tZzyO61ejAmC4uFLp/FLaA6+bPkye0jBzaG8nOxqhty05l5ptrlER0uN1KTFEjgn8uQ1OmrA6FAYdxN+zErcvdU3Q1Y8R2aYEPRxTB15k4AthAYA8Im4aPuPClOF6HnTNbGp/wpqYcNBjnUaYoTMylptl3NgfZIAKMCj8WLIiHngCEtk5Nmkju4BFBsW0ZHo3yt+7o8fi5PvT979N7iwm6jPWnulS4Q63EpXOHBIGv7acz0IByBv147Po1TVK6a9V8AdQyLUM/SP15MlPvmLaig++kxQwDNx3pSCPpYjl3JbQXI=
